# Generated by Django 5.2.1 on 2025-05-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default=111111, unique=True),
            preserve_default=False,
        ),
    ]
